###
GET http://localhost:4004/bookservice/Books
Authorization: Basic test1:password

###
POST http://localhost:4004/bookservice/Books
Content-Type: application/json

{

    "ID": 503,
    "author_ID": 101,
    "title": "New Book",
    "genre": "Comic3",
    "availiableStock": 167
  }

###
GET http://localhost:4004/bookservice/health
Authorization: Basic test1:password

###
GET http://localhost:4004/bookservice/Books/43c139cf-ec12-4b02-814a-8aa2386811e0/getStock
Authorization: Basic test1:password